apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
    spec:
      containers:
      - image: localhost:5000/demo-293781008328a00955c916a466ee51430ad60f0b
        name: demo-go
        ports:
        - containerPort: 8888
