apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
    spec:
      containers:
      - image: localhost:5000/demo-4cbf91b931b4a7d04d16a6142c1b9d07e8965146
        name: demo-go
        ports:
        - containerPort: 8888
