apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
    spec:
      containers:
      - image: localhost:5000/demo-ea4967138e5eff993d14ab9751e016d55360a1f1
        name: demo-go
        ports:
        - containerPort: 8888
