apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
    spec:
      containers:
      - image: localhost:5000/demo-c4206c7ad201113ebaf5dc64001699312caf3b81
        name: demo-go
        ports:
        - containerPort: 8888
