apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
    spec:
      containers:
      - image: localhost:5000/demo-2760d5cf660c1b018d4a9418747b948385414143
        name: demo-go
        ports:
        - containerPort: 8888
